### ISSUE TITLE
Distribute though f-droid

### ISSUE THREAD

**Issue by arthurlutz** [emoncms/AndroidApp#1]
https://f-droid.org/ is a an installable catalogue of FOSS (Free and Open Source Software) applications for the Android platform.

It would be awesome for the emoncms android application to be distributed through f-droid (and also publish the APK somewhere else could be nice).

**Comment by JumpMaster** [comment]
I've used f-droid before when needing to download software that has been removed from the Play store such as ad blockers. I would always prefer to download software via the Play store where it has been checked and updates are pushed out automatically.

Why would you prefer to use f-droid over the Play store?

**Comment by arthurlutz** [comment]
Sorry I didn't reply sooner. 

I have a preference for f-droid over play store because there it gives a clear indication that the application is open source and that there might be a community that I can interact with, an issue tracker where I can report bugs or submit feature ideas.

The other scenario where this is interesting is for alternative ROMs where the play store has been removed (cyanogen mod or replicant http://www.replicant.us/ for example) for people who want to have less proprietary software and/or no google account. 

Last but not least, I think being on f-droid would give emoncms some publicity, I know a bunch of geeks who closely  watch the "What's new" applications arriving on f-droid and might look into emoncms when seeing this one arrive there. It's an ecosystem.
