### ISSUE TITLE
App enhancements

### ISSUE THREAD

**Issue by tombarks** [emoncms/AndroidApp#11]
Hi guys, good job on the app. Just wondering if I can suggest/contribute to some improvements. I'm using emoncms to log my home temperatures. I also use a feed to set a heating system target temperature demand for my home underfloor heating controller. The controller fetches the demand from emoncms.org periodically and then, assuming its a sensible demand, controls my heating to that temperature.

I've written my own android app to retrieve and set the demand which works fine. I would like some other features such as showing temperature charts etc. However before I consider developing that I was wondering if it would be possible to extend this app with for example 'My Heating'? With features for viewing home temperatures and setting various temperature demands.

I would be happy to contribute. Or indeed just to make requests for others to implement if that was a more efficient way to do things.

**Comment by glynhudson** [comment]
Hi Tom,

Thanks for your kind words. Good to hear you are finding Emoncms and the app useful. The android app was developed by @JumpMaster. 

Awesome, adding a temperature graph view would be a nice! @TrystanLea make some mockups of future mobile add development which includes a MyTemperature mockup. See forum thread: https://community.openenergymonitor.org/t/mobile-app-emoncms-mobile-dash-mockup/2018

Another nice addition would be the ability to view _any_ feed from your Emoncms account via the app. Like on recently launched the iOS app: https://community.openenergymonitor.org/t/ios-app-thoughts/1799/31?u=glyn.hudson

I am aware that forum user [tamsin](https://community.openenergymonitor.org/users/tamsin/activity) is working on multi user / multi Emoncms account support for the Android app.

As you can see most discussion regarding development takes place on our forum. I recommend you start a thread in the Emoncms > mobile section and tag with 'android' to avoid confusion with iOS! 

https://community.openenergymonitor.org/c/emoncms/mobile-app

I will close this issue, feel free to open a new dev specific issue 👍
