### ISSUE TITLE
When tapping on '3H' to view last 3hrs of data the display does not fill the screen

### ISSUE THREAD

**Issue by glynhudson** [emoncms/AndroidApp#17]
https://community.openenergymonitor.org/t/emoncms-android-app-v2-0-0-open-beta-testing/3373/16?u=glyn.hudson

![](https://community.openenergymonitor.org/uploads/default/original/2X/2/279afd43a9880bdeeafcc12ddbe4fe53acfc854c.png)

**Comment by tamslinn** [comment]
Possibly related to https://github.com/PhilJay/MPAndroidChart/issues/2646

**Comment by tamslinn** [comment]
Fixed
