### ISSUE TITLE
Support old versions of android

### ISSUE THREAD

**Issue by arthurlutz** [emoncms/AndroidApp#2]
Tried to install emoncms on an old phone that has android 2.x (I can check if you need more specific information about the device), but it was not available for the device. 

It would be a shame to not support old deprecated devices which could be reused as a "display" for emoncms data. 

Is this a technical restriction ? Or the google play compilation that works that way ? Maybe related to #1

**Comment by JumpMaster** [comment]
There's always a trade off between using the latest features and supporting legacy devices. Android changed a lot in version 3.0 with those devices later been upgraded to 4.0 so it made sense to support 4.0+.

Android 2.x is installed on 3.2% of Android devices where as 4.X+ is on 96.5% of devices. The extra effort involved to support that last 3% just doesn't make sense I'm afraid.
