### ISSUE TITLE
Few extra strings to be translated

### ISSUE THREAD

**Issue by glynhudson** [emoncms/AndroidApp#25]
https://community.openenergymonitor.org/t/emoncms-android-app-v2-0-1-open-beta-testing/3373/38?u=glyn.hudson

**Comment by tamslinn** [comment]
I've done a pull request with the following new strings for translation:

    <string name="cancel">CANCEL</string>
    <string name="settings_confirm_delete_account">Are you sure you want to delete this account? All settings will be lost.</string>
    <string name="settings_confirm_delete_page">" Are you sure you want to delete this page?"</string>
    <string name="settings_title_accounts">ACCOUNTS</string>
    <string name="settings_title_add_account">Add Account</string>
    <string name="settings_title_page_name">Page name</string>

I've just added the English version to each of the language files, I had a quick try with google translate but didn't get answers consistent with existing translations!

**Comment by glynhudson** [comment]
Fantastic! [merged](https://github.com/emoncms/AndroidApp/commit/8e8bf6b75d2092c8218594c4857320ab22ccf5f9) I'm no translation expert either, hopefully we can ask:   

~@JBecker32 to help with the [german strings](https://github.com/emoncms/AndroidApp/blob/master/app/src/main/res/values-de/strings.xml)?~
Update: [extra DE strings have been translated by @JBecker32]  (https://github.com/emoncms/AndroidApp/commit/2087000c784d7c6e8c52b137159bd42dcb88a369) 👍 

~@bidouilleur31 to help with the [french strings](https://github.com/emoncms/AndroidApp/blob/master/app/src/main/res/values-fr/strings.xml) and maybe also dutch strings [dutch strings](https://github.com/emoncms/AndroidApp/blob/master/app/src/main/res/values-nl/strings.xml) ? I think the Dutch strings are still just a copy of the German strings, more translation work may be needed here. Do you know anyone else who can help?~
[NL strings translated by @bidouilleur31](https://github.com/emoncms/AndroidApp/commit/2f0f32a29f2977aaaaafb447646c16acfcb00617)
[FR strings translated by @bidouilleur31](https://github.com/emoncms/AndroidApp/commit/8c5340e52ced698366ac9cd8eb93ba4c00b00498)


@gablau to help with the [Italien strings](https://github.com/emoncms/AndroidApp/blob/master/app/src/main/res/values-it/strings.xml)?

Thanks a lot, we're so close to a V2 release 🥇 💯 

**Update:** Links above have now been fixed.

**Comment by gablau** [comment]
Here I am, the Italian translation is ready!
[https://github.com/emoncms/AndroidApp/pull/32](url)

**Comment by glynhudson** [comment]
Great! Thanks so much. I'll get a beta update released with all the updated strings 👍
