### ISSUE TITLE
Beta: Debugging random force close

### ISSUE THREAD

**Issue by glynhudson** [emoncms/AndroidApp#27]
When the app is kept running 24/7 on a wall mounted nexus 7 tablet after a period of time (28hrs in this case) the app seems to force close. I have manged the capture the logs using [log cat](https://play.google.com/store/apps/details?id=com.nolanlawson.logcat&hl=en_GB) on a rooted device to try and debug what's causing this.

The old V1 app has been tested to run for many months 24/7 which screen-on on my wall-mount tablet without issue. While this may seem like a minor issue, it's a very common use case for the app to be used as an always-on wall-mount display therefore it's very important that the app does not force close.

Here are are the log files lines of interest obtained by filtering by 'emoncms'

`$cat 2017-04-04-13-18-24.txt  | grep emoncms`

```
04-05 17:09:45.791 I/EMONCMS:URL( 2198): mGetPowerRunner:http://emonpi/emoncms/feed/fetch.json?apikey=d3d92676005672ef4f31830fbdc0b500&ids=1,34
04-05 17:09:48.556 I/EMONCMS:URL( 2198): mGetPowerHistoryRunner:http://emonpi/emoncms/feed/data.json?apikey=d3d92676005672ef4f31830fbdc0b500&id=1&start=1491408533000&end=1491408588556&interval=14&skipmissing=1&limitinterval=1
04-05 17:09:48.557 I/EMONCMS:URL( 2198): mGetPowerRunner:http://emonpi/emoncms/feed/fetch.json?apikey=d3d92676005672ef4f31830fbdc0b500&ids=87,88
04-05 17:09:58.112 I/WindowState(  499): WIN DEATH: Window{75d4912 u0 org.emoncms.myapps/org.emoncms.myapps.MainActivity}
04-05 17:09:58.180 W/InputDispatcher(  499): channel '75d4912 org.emoncms.myapps/org.emoncms.myapps.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
04-05 17:09:58.180 E/InputDispatcher(  499): channel '75d4912 org.emoncms.myapps/org.emoncms.myapps.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
04-05 17:09:58.186 I/ActivityManager(  499): Process org.emoncms.myapps (pid 2198) has died
04-05 17:09:58.274 W/InputDispatcher(  499): Attempted to unregister already unregistered input channel '75d4912 org.emoncms.myapps/org.emoncms.myapps.MainActivity (server)'
04-05 17:09:58.373 W/ActivityManager(  499): Force removing ActivityRecord{21f17558 u0 org.emoncms.myapps/.MainActivity t78}: app died, no saved state
04-05 17:40:03.497 W/PackageManager(  672): Failure retrieving resources for org.emoncms.myapps: Resource ID #0x0
```
The mains issue seems to be:

`W/InputDispatcher(  499): channel '75d4912 org.emoncms.myapps/org.emoncms.myapps.MainActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9`

Full log is attached. 

Can anyone with more Android knowledge than me figure out what could be causing the 'channel' to close? @JumpMaster  @tamslinn ?

[logcat_and_device_info.zip](https://github.com/emoncms/AndroidApp/files/902203/logcat_and_device_info.zip)

**Comment by tamslinn** [comment]
Agreed this is not good enough! 

There are some out of memory errors in the full log just before the "WIN DEATH" line in your excerpt. I'll try and work out what I have done wrong...

**Comment by glynhudson** [comment]
Agh, very sorry to create more work. We're so close to a release! 

Sounds like it could be tricky to debug this, any ideas how best to debug an issue like this @JumpMaster ?

**Comment by JumpMaster** [comment]
Assuming this is a memory leak.  Outputting the memory usage with each collection would be useful.  Could prove it was a memory leak and prove when it's fixed.  Will do some Googling now.

**Comment by tamslinn** [comment]
Do you keep it on one page @glynhudson or would you have swiped frequently between pages during the time it was running?

**Comment by glynhudson** [comment]
I setup two pages, but didn't change between the pages at all during the 28hr period. I'm pretty sure I didn't touch it once between opening the app and the force close. I have setup another test, I'm currently about 20hrs in....

Update: app force close after 20-30 hrs. I'm testing on a Nexus 7 2012 with Android 5.1.1

**Comment by tamslinn** [comment]
Thanks - I'm now doing some logging of memory use and it is definitely creeping up, I think related to loading the data for the power chart. I'm guessing I've missed something when refactoring. I'll dig into it a bit more and let you know how I get on!

**Comment by glynhudson** [comment]
I remember you mentioning that the pages either side of the active page are loaded, are they refreshed continuously? If os maybe after a time period, 60s or so the app could focus on only refreshing the current page. This will result in a little lag when swiping pages if the app has been loaded for a while but should not be too bad?

**Comment by tamslinn** [comment]
Hi @glynhudson  I will have a look at that as would definitely reduce unnecessary network traffic. However I think if there is a memory leak then not keeping the side pages active will just make the app last 2-3 times longer before crashing. I have been looking at memory dumps in android studio and with some help from Dave spotted a potential issue. Could you generate an apk from my repository and try running it on your tablet to test it? I'll try and dig out an old phone to leave running, at the moment I haven't got anywhere to test running 24/7! Thanks

**Comment by glynhudson** [comment]
Sure, I'll do that right away. Thanks a lot for trying to debug. I have tested running 24/7 on couple of different tablets and the app seems to consistently force close after about 48hrs

**Comment by glynhudson** [comment]
**Update:** I left the test (running your branch) running over the Easter weekend. I was delighted when I came into work this morning and the Emoncms app was still running! The app had been running for 5 days. However, by midday today the app sees to have force closed :-/ . In total the app ran from 7pm on 2th April to 12pm on 18th April total = 137hrs. This is a big improvement on 48hrs.

I will merge your branch changes since this is a big improvement and get a beta update released. This will allow me to more easily test on more devices and get some more data points from other users.

It seems I am the only one to notice this issue, I'm guessing the other beta testers are not running the beta on wall mounted 24/7 devices. 

There does seem to be some issues with the app loosing it's settings and formatting of numbers. Both issues I have been unable to re-create: https://community.openenergymonitor.org/t/emoncms-android-app-v2-0-1-open-beta-testing/3373/82

**Comment by tamslinn** [comment]
Well definitely an improvement, but not good enough. Should we leave this issue open? I'll get it running on an phone so I can get a memory dump after it's been running for a few days.

**Comment by tamslinn** [comment]
@glynhudson I'll take a look at the formatting etc when I get a mo - it's half term so kids around which means little free time for tinkering!

**Comment by glynhudson** [comment]
No rush! V2.0.7 is rolling out to beta channel, this contains your caching fix:

https://github.com/emoncms/AndroidApp/releases/tag/2.0.7

I'll setup a test on some other devices. I have re-opened issue for the moment. 

It seems the settings saving issue and font issues seems to be affecting Samsung s7 have you been able to get the device emulator to work in Android studio? This would be useful to help test different devices. I think I need to fiddle a setting in the BIOS...

**Comment by Paul-Reed** [comment]
"It seems the settings saving issue and font issues seems to be affecting Samsung s7 "

Not exclusively Samsung, add my HTC One M8 to the list.

**Comment by tamslinn** [comment]
Thanks, I'll try get the emulator working! I've made separate issues for the font size and settings to keep things tidy on this issue:
* https://github.com/emoncms/AndroidApp/issues/45
* https://github.com/emoncms/AndroidApp/issues/46
