### ISSUE TITLE
Unable to download feed list when I try to configure "My Electric Feeds"

### ISSUE THREAD

**Issue by arthurlutz** [emoncms/AndroidApp#3]
When I try to configure "My Electric Feeds" I get the following error : 

```
Error

Unable to download feed list. Please check URL and API settings as well as connectivity to emoncms
```

Tried : 
- the connectivity is fine, I have emoncms opened in a browser
- the read API key, the write API key
- http and https

I don't see anything related in my access log or error log on my self-hosted emoncms. Any other things I could look at ?

**Comment by glynhudson** [comment]
Sorry for the slow reply. Does the MyElectric graph work on your Emoncms server. What Emoncms server are you using? Emoncms.org?
