### ISSUE TITLE
Use QR code instead of API key

### ISSUE THREAD

**Issue by Paul-Reed** [emoncms/AndroidApp#4]
@JumpMaster a [pull request](https://github.com/emoncms/emoncms/pull/514) by @AndyTaylorTweet has suggested using a QR code to register the API key in the Android App,  and has provided the necessary emoncms changes to facilitate this (untested at this time).
Is this a viable option for the Android App, to scan and use a QR code?
_There is little point in merging the changes unless this option is of use._

Paul

**Comment by glynhudson** [comment]
Setup using QR code has been included in 1.2.2 release: https://github.com/emoncms/AndroidApp/releases/tag/1.2.2

This has now been promoted to production in Google Play.

Thanks to @JumpMaster and @AndyTaylorTweet their hard work
