### ISSUE TITLE
Beta: Settings are lost on some devices

### ISSUE THREAD

**Issue by tamslinn** [emoncms/AndroidApp#45]
See https://community.openenergymonitor.org/t/emoncms-android-app-v2-0-1-open-beta-testing/3373/81

**Comment by tamslinn** [comment]
Just had a look at the commit history and I think this may be to do with the addition of the custom currency symbol - the page settings are stored in json and it could be throwing an error trying to read a setting which was not there previously.

**Comment by glynhudson** [comment]
Ah good spot, the issue has only started happening recently. That would explain it. 

@gablau  have you notices this issue, do you think you could take a look?  Do you think I should revert PR #38 ?

**Comment by tamslinn** [comment]
It won't happen with people upgrading from V1 to V2 format as the JSON is new and created by the upgrade code. And should only happen once for the beta testers

**Comment by glynhudson** [comment]
If it only happened once to the beta testers it would not be an issue. However it seems whenever the app is (force) closed the settings are lost. I am able to re-create this:

https://www.youtube.com/watch?v=cPj4Tdxrwlg

**Comment by tamslinn** [comment]
ah ok, maybe more of a bug then. I haven't got the latest app running at the mo.

**Comment by tamslinn** [comment]
@glynhudson this has fixed it for me, can you test when you get a mo?

**Comment by glynhudson** [comment]
Yup fixed. Nice work! 🥇  👍 

I'll get a V2.0.8 beta update pushed out with these fixes right away.

Thanks so much. We're so close to a release now!
