### ISSUE TITLE
Beta: untranslatable string

### ISSUE THREAD

**Issue by joyrider3774** [emoncms/AndroidApp#47]
Hey,

as i don't know how to fix this i'm creating an issue.

There's is at least one untranslateable string i found in the current code here https://github.com/emoncms/AndroidApp/blob/master/app/src/main/java/org/emoncms/myapps/settings/AccountListFragment.java#L44

as can been seen on my video here from version 2.0.6 (dealing with some problems it has like lost settings + also the text being too big) here at minute 3:12 https://www.youtube.com/watch?v=79xcpMbDGng&feature=youtu.be

**Comment by tamslinn** [comment]
This is translatable now, added in English in all files
