### ISSUE TITLE
Settings option disappears from sidebar when lots of pages are created 

### ISSUE THREAD

**Issue by glynhudson** [emoncms/AndroidApp#53]
As reported on the forum by @joyrider3774. [See forum post](https://community.openenergymonitor.org/t/emoncms-android-app-v2-0-1-open-beta-testing/3373/90?u=glyn.hudson)

Could an easy fix be to move the setting option to the top of the list? 

![](https://community.openenergymonitor.org/uploads/default/optimized/2X/c/c6f02eaa6549562ae1069ee26b6e7b109a81745f_1_281x500.png)

**Comment by joyrider3774** [comment]
i should add that the problem only occurs when you have no connection. The grey bar with "verbindings probleem" is drawn over the  "settings" menu item, making it not accessible. There is no problem when you have no connection problems. See the forum post to know how i had gotten myselve into that trouble

**Comment by TrystanLea** [comment]
is this still an issue? @glynhudson
