### ISSUE TITLE
page name : to long -> pushing down content

### ISSUE THREAD

**Issue by bidouilleur31** [emoncms/AndroidApp#61]
when changing/adding a page name, as it isn't limited in length,  you can create 'overflow'
See added images where you see I by accident typed a few carrier returns pushing the title down.
As a side effect on the graphic it is pushing down the whole bloc down.
None geeks might end with weird situations.
Possible to limit size on the container ?

![feed1](https://cloud.githubusercontent.com/assets/19654579/25311416/841b810a-2800-11e7-9641-2e8cda58aade.jpg)
![feed](https://cloud.githubusercontent.com/assets/19654579/25311417/88ced9cc-2800-11e7-9f1c-44aa724711ff.jpg)

**Comment by glynhudson** [comment]
This is actually a feature! It allows users to add more information if required about a particular page. Agree, it would be a good idea to limit to a sensible number of lines e.g. 50% of display. However, I don't think this is a big issue.

![screenshot_20170615-130612](https://user-images.githubusercontent.com/758844/27180508-b98b218e-51cb-11e7-881e-0cf180fdf145.png)
