### ISSUE TITLE
App craches with nulls

### ISSUE THREAD

**Issue by chaveiro** [emoncms/AndroidApp#7]
When the app performs:
http://server/feed/fetch.json?apikey=xxx&ids=173,173
And the answer is:
[null,null]

The app crashes and ends without further notice.

(Null is a valid value, i will bring that back to emoncms later.)

**Comment by JumpMaster** [comment]
Thanks for testing. I've added an isNumeric() check.

Could you check again with this version please.

https://www.dropbox.com/s/2y47staiikosyux/emoncms_fr_test.apk?dl=0

**Comment by chaveiro** [comment]
That test version fixed it!

I just have other question, when choosing the feeds it gives only 3 options AUTO/Test-FINA-KWH/ P kwhd

But i have way more accomulative feeds. Why is it just showing me this 2 (plus Auto)?

Response to my feed/list.json :
`[{"id":"1","name":"Voltage","userid":"1","tag":"Alta","datatype":"1","public":"1","size":"761451574","engine":"0","time":"1464902617","value":"247.32","processList":""},{"id":"3","name":"Frequency","userid":"1","tag":"Alta","datatype":"1","public":"1","size":"762447499","engine":"0","time":"1464902617","value":"50.01","processList":""},{"id":"4","name":"Current","userid":"1","tag":"Alta","datatype":"1","public":"1","size":"759447536","engine":"0","time":"1464902617","value":"1.33","processList":""},{"id":"5","name":"Active Power","userid":"1","tag":"Alta","datatype":"1","public":"1","size":"759587791","engine":"0","time":"1464902617","value":"295.05","processList":""},{"id":"6","name":"Aparent Power","userid":"1","tag":"Alta","datatype":"1","public":"1","size":"759152001","engine":"0","time":"1464902617","value":"329.91","processList":""},{"id":"7","name":"Power Factor","userid":"1","tag":"Alta","datatype":"1","public":"1","size":"761973341","engine":"0","time":"1464902617","value":"0.89","processList":""},{"id":"9","name":"Act Power Histogram","userid":"1","tag":"Alta-Calculado","datatype":"3","public":"1","size":"511736","engine":"0","time":"1464902617","value":"300","processList":""},{"id":"8","name":"PIN Status","userid":"1","tag":"Alta","datatype":"1","public":"1","size":"85145","engine":"0","time":"1464876193","value":"0","processList":""},{"id":"10","name":"Kwhd","userid":"1","tag":"Alta-Calculado","datatype":"2","public":"1","size":"260874","engine":"0","time":"1464902617","value":"2.52497","processList":""},{"id":"163","name":"S Aparent Power VA","userid":"1","tag":"Olaias","datatype":"1","public":"0","size":"73946952","engine":"0","time":"1464902620","value":"230.85","processList":""},{"id":"162","name":"PIN Status","userid":"1","tag":"Olaias","datatype":"1","public":"0","size":"73452","engine":"0","time":"1464876191","value":"1","processList":""},{"id":"161","name":"Power Factor","userid":"1","tag":"Olaias","datatype":"1","public":"0","size":"74180451","engine":"0","time":"1464902620","value":"0.89","processList":""},{"id":"160","name":"U Voltage","userid":"1","tag":"Olaias","datatype":"1","public":"0","size":"74180901","engine":"0","time":"1464902620","value":"243.94","processList":""},{"id":"73","name":"V Voltage","userid":"1","tag":"Lumiar","datatype":"1","public":"0","size":"142655560","engine":"0","time":"1464902616","value":"242.94","processList":""},{"id":"164","name":"P Active Power","userid":"1","tag":"Olaias","datatype":"1","public":"0","size":"74180406","engine":"0","time":"1464902620","value":"204.77","processList":""},{"id":"157","name":"RH","userid":"1","tag":"Alta","datatype":"1","public":"1","size":"6723004","engine":"0","time":"1464902579","value":"45.38","processList":""},{"id":"72","name":"S Aparent Power VA","userid":"1","tag":"Lumiar","datatype":"1","public":"0","size":"142528944","engine":"0","time":"1464902616","value":"566","processList":""},{"id":"165","name":"I Current","userid":"1","tag":"Olaias","datatype":"1","public":"0","size":"73924415","engine":"0","time":"1464902620","value":"0.95","processList":""},{"id":"166","name":"HZ Frequency","userid":"1","tag":"Olaias","datatype":"1","public":"0","size":"74181421","engine":"0","time":"1464902620","value":"50.09","processList":""},{"id":"167","name":"\u00baC","userid":"1","tag":"Olaias","datatype":"1","public":"0","size":"5330840","engine":"0","time":"1464902607","value":"25.08","processList":""},{"id":"75","name":"PIN Status","userid":"1","tag":"Lumiar","datatype":"1","public":"1","size":"3567922","engine":"0","time":"1464897906","value":"1","processList":""},{"id":"158","name":"RH","userid":"1","tag":"Lumiar","datatype":"1","public":"0","size":"6208067","engine":"0","time":"1464902601","value":"50.92","processList":""},{"id":"156","name":"\u00baC","userid":"1","tag":"Alta","datatype":"1","public":"1","size":"6723022","engine":"0","time":"1464902579","value":"24.08","processList":""},{"id":"74","name":"HZ Frequency","userid":"1","tag":"Lumiar","datatype":"1","public":"0","size":"142602502","engine":"0","time":"1464902616","value":"50.38","processList":""},{"id":"149","name":"TEST-FINA-KWH","userid":"1","tag":"Alta-Calculado","datatype":"1","public":"0","size":"21069248","engine":"5","time":"1464902617","value":"1094.01","processList":""},{"id":"148","name":"test1","userid":"1","tag":"Virtual","datatype":"1","public":"0","size":"0","engine":"7","time":null,"value":null,"processList":""},{"id":"168","name":"node:99:1","userid":"1","tag":"Node 99","datatype":"1","public":"0","size":"0","engine":"8","time":"1451414534","value":"1100","processList":""},{"id":"76","name":"P Active Power","userid":"1","tag":"Lumiar","datatype":"1","public":"0","size":"142599874","engine":"0","time":"1464902616","value":"455.17","processList":""},{"id":"77","name":"I Current","userid":"1","tag":"Lumiar","datatype":"1","public":"0","size":"142603508","engine":"0","time":"1464902616","value":"2.33","processList":""},{"id":"78","name":"Power Factor","userid":"1","tag":"Lumiar","datatype":"1","public":"0","size":"142529950","engine":"0","time":"1464902616","value":"0.8","processList":""},{"id":"79","name":"Act Power Histogram","userid":"1","tag":"Lumiar-Calculado","datatype":"3","public":"0","size":"271787","engine":"0","time":"1464902616","value":"450","processList":""},{"id":"80","name":"kWhd","userid":"1","tag":"Lumiar-Calculado","datatype":"2","public":"0","size":"101138","engine":"0","time":"1464902616","value":"10.2867","processList":""},{"id":"99","name":"Lumiar Max Voltage","userid":"1","tag":"Node:20","datatype":"2","public":"1","size":"68054","engine":"0","time":"1464840107","value":"244.42","processList":""},{"id":"100","name":"Lumiar Min Voltage","userid":"1","tag":"Node:20","datatype":"2","public":"0","size":"67946","engine":"0","time":"1464851419","value":"234.69","processList":""},{"id":"159","name":"\u00baC","userid":"1","tag":"Lumiar","datatype":"1","public":"0","size":"6208103","engine":"0","time":"1464902601","value":"23.57","processList":""},{"id":"119","name":"Teste Lumiar P Active Power","userid":"1","tag":"Lumiar","datatype":"1","public":"0","size":"97074258","engine":"0","time":"1464902616","value":"455.17","processList":""},{"id":"113","name":"Alta bi week full","userid":"1","tag":"Alta Bi Horario-Virtual","datatype":"1","public":"0","size":"0","engine":"7","time":1464902620,"value":295.05,"processList":"53:5,schedule__if_not_schedule_null:5"},{"id":"112","name":"Alta bi week empty","userid":"1","tag":"Alta Bi Horario-Virtual","datatype":"1","public":"0","size":"0","engine":"7","time":1464902620,"value":null,"processList":"53:5,schedule__if_not_schedule_null:4"},{"id":"118","name":"Daily Virtual Feed","userid":"1","tag":"Virtual","datatype":"2","public":"0","size":"0","engine":"7","time":1464902620,"value":1,"processList":"3:1"},{"id":"169","name":"Post Errors","userid":"1","tag":"Alta","datatype":"1","public":"0","size":"5037184","engine":"8","time":"1464902617","value":"0","processList":""},{"id":"170","name":"Post errors","userid":"1","tag":"Olaias","datatype":"1","public":"0","size":"74056442","engine":"0","time":"1464902620","value":"0","processList":""},{"id":"171","name":"Kwhd","userid":"1","tag":"Olaias-Calculado","datatype":"2","public":"0","size":"5914","engine":"0","time":"1464902620","value":"4.68015","processList":""},{"id":"172","name":"Act Power Histogram","userid":"1","tag":"Olaias-Calculado","datatype":"3","public":"0","size":"126186","engine":"0","time":"1464902620","value":"200","processList":""},{"id":"174","name":"Post errors","userid":"1","tag":"Lumiar","datatype":"1","public":"0","size":"50146812","engine":"0","time":"1464902616","value":"0","processList":""},{"id":"173","name":"P kwhd","userid":"1","tag":"Node 30","datatype":"2","public":"0","size":"0","engine":"2","time":null,"value":null,"processList":""},{"id":"176","name":"Dummy","userid":"1","tag":"Alta","datatype":"1","public":"0","size":"0","engine":"7","time":1464902620,"value":null,"processList":"36:0"},{"id":"177","name":"test","userid":"1","tag":"Alta-Calculado","datatype":"1","public":"0","size":"0","engine":"7","time":1464902620,"value":1.123595505618,"processList":"59:7"}]`

**Comment by JumpMaster** [comment]
It only shows engine type 2, 5, and 6.

Line 132
https://github.com/emoncms/AndroidApp/blob/master/app/src/main/java/org/emoncms/myapps/MyElectricSettingsFragment.java

**Comment by chaveiro** [comment]
Why? Engine is should not be relevant to the output data.
I do use mysql engine due to best portability.
