### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by erdo** [emoncms/AndroidApp#71]
Hi, what's the status of this app at the moment? it's not been updated for a while (but if it works, no need to fix it I guess!).

The version on the play store does need a bit of an update though, it's not downloadable on an Android 10 device.

Did development move to a different git repo or app maybe?

**Comment by glynhudson** [comment]
App development is not our focus right now, we're focusing on the Emoncms web experience. However, the app has just been updated to support Android 14. It's open-source, feel free to submit PRs
