### ISSUE TITLE
Creating hard coding 'fork' of the app for a particuar application

### ISSUE THREAD

**Issue by glynhudson** [emoncms/AndroidApp#8]
Hi Kev, 

Sorry to bother you, I just thought I would let you know what I'm trying to do. I would appreciate any guidance you could give me as to the best way to achieve this. 

We are involved in the monitoring of a local hydro system and a [local energy grid](http://www.energylocal.co.uk/), where signed up community members will receive low-cost electricity when the hydo is running. For the purpose of notifing users when the hydro is on/off I propose creating a customised version of the Emoncms Android app with customised name, logo and API key and feed ID of the hydro system data on emoncms.org hard-coded. Obviously, the app will need to be renamed from Emoncms > Hafod y Porth (name of the hydro). It seems there is a [semi-automated way to rename a project using Android Studio](http://stackoverflow.com/questions/16804093/android-studio-rename-package). 

I have made a start on this and have successfully set the API key and feed ID's by entering default values into the config .xml files, see my commit to my fork. 
https://github.com/emoncms/AndroidApp/compare/master...glynhudson:master

I have setup Android Studio and have the modified version running successfully on my phone. 

The part I am struggling with his how to hide the preference items for API key, feed ID selection etc. I have tried commenting out the relevant preference sections in [me_preferences.xml](https://github.com/emoncms/AndroidApp/blob/master/app/src/main/res/xml/me_preferences.xml) however this created errors when other parts of the code tried to reference the missing preference items. Would it be possible to just hide specific preference items e.g:

http://stackoverflow.com/questions/4081533/how-to-remove-android-preferences-from-the-screen

```
PreferenceCategory notificationsCategory = (PreferenceCategory) findPreference("notifications_category");
notificationsCategory.removePreference(mPollPref);
```

**Comment by JumpMaster** [comment]
Hi Glyn,

Sounds like a cool project!

I would hard code to key/feed ids slightly differently. In MyElectricFragment.java I would change the following.

Line 68
static String emoncms_url = "https://myhardcodedurl";
static String emoncms_apikey = "myhardcodedurl";

Line 86 - hard code feed ids here
int wattFeedId = 0;
int kWhFeelId = 0;

Lines 504 through 508 can be commented out as there no need to loads the preferences anymore.

Then remove the options from the preference XML file.

You'll need to sign the app with a key. 

If you want me to take a look at it let me know.

Kev

On 6 Jun 2016 16:25, Glyn Hudson notifications@github.com wrote:

Hi Kev,

Sorry to bother you, I just thought I would let you know what I'm trying to do. I would appreciate any guidance you could give me as to the best way to achieve this.

We are involved in the monitoring of a local hydro system and a local energy gridhttp://www.energylocal.co.uk/, where signed up community members will receive low-cost electricity when the hydo is running. For the purpose of notifing users when the hydro is on/off I propose creating a customised version of the Emoncms Android app with customised name, logo and API key and feed ID of the hydro system data on emoncms.org hard-coded. Obviously, the app will need to be renamed from Emoncms > Hafod y Porth (name of the hydro). It seems there is a semi-automated way to rename a project using Android Studiohttp://stackoverflow.com/questions/16804093/android-studio-rename-package.

I have made a start on this and have successfully set the API key and feed ID's by entering default values into the config .xml files, see my commit to my fork.
master...glynhudson:masterhttps://github.com/emoncms/AndroidApp/compare/master...glynhudson:master

I have setup Android Studio and have the modified version running successfully on my phone.

The part I am struggling with his how to hide the preference items for API key, feed ID selection etc. I have tried commenting out the relevant preference sections in me_preferences.xmlhttps://github.com/emoncms/AndroidApp/blob/master/app/src/main/res/xml/me_preferences.xml however this created errors when other parts of the code tried to reference the missing preference items. Would it be possible to just hide specific preference items e.g:

http://stackoverflow.com/questions/4081533/how-to-remove-android-preferences-from-the-screen

PreferenceCategory notificationsCategory = (PreferenceCategory) findPreference("notifications_category");
notificationsCategory.removePreference(mPollPref);

**Comment by glynhudson** [comment]
Thanks a lot for your response. I have updated my fork to reflect your recommended method  to hard code settings. This is working great :+1:  

see: https://github.com/emoncms/AndroidApp/compare/master...glynhudson:master

However when i try and commend out / remove the preferences from the menu I get dependancy errors. e,g  commenting out 

```
    <!--
    <PreferenceCategory
        android:title="@string/settings_title_emoncms_connectivity">
        <Preference
            android:key="scanqrcode"
            android:title="@string/settings_title_scanqrcode"
            android:summary="@string/settings_summary_scanqrcode"/>

        <EditTextPreference
            android:key="emoncms_url"
            android:title="@string/settings_title_emoncms_url"
            android:summary="@string/settings_summary_emoncms_url"
            android:defaultValue="emoncms.org"/>

        <EditTextPreference
            android:key="emoncms_apikey"
            android:title="@string/settings_title_emoncms_apikey"
            android:summary="@string/settings_summary_emoncms_apikey"/>


        <CheckBoxPreference
            android:key="emoncms_usessl"
            android:title="@string/settings_title_emoncms_usessl"
            android:summary="@string/settings_summary_emoncms_usessl"
            android:defaultValue="true"/>
    </PreferenceCategory>
    -->
```

Results in 

```
FATAL EXCEPTION: main
                                                                    Process: org.emoncms.myapps, PID: 26710
                                                                    java.lang.NullPointerException: Attempt to invoke virtual method 'void android.preference.Preference.setOnPreferenceClickListener(android.preference.Preference$OnPreferenceClickListener)' on a null object reference
                                                                        at org.emoncms.myapps.SettingsFragment.onResume(SettingsFragment.java:44)
                                                                        at android.app.Fragment.performResume(Fragment.java:2263)
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1008)
                                                                        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
                                                                        at android.app.BackStackRecord.run(BackStackRecord.java:793)
                                                                        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1537)
                                                                        at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
                                                                        at android.os.Handler.handleCallback(Handler.java:746)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                        at android.os.Looper.loop(Looper.java:148)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
```

Is there a way the setting  could just be _hidden_ so they are there to keep th build happy but they will be hidden from the user? 

---

**UPDATE**: Fixed the error above by removing scanqrcode from `Settingsfragment.java`

```
  /*
        Preference button = findPreference("scanqrcode");
        button.setOnPreferenceClickListener(new Preference.OnPreferenceClickListener() {
            @Override
            public boolean onPreferenceClick(Preference preference) {
                // launch barcode activity.
                Intent intent = new Intent(getActivity(), BarcodeCaptureActivity.class);
                startActivityForResult(intent, RC_BARCODE_CAPTURE);
                return true;
            }
        });
        */
```

**Comment by glynhudson** [comment]
Issues have been solved, and hard coded and renamed [hydro monitoring app](https://play.google.com/store/apps/details?id=org.cydynni_hydro.myapps&utm_source=global_co&utm_medium=prtnr&utm_content=Mar2515&utm_campaign=PartBadge&pcampaignid=MKT-Other-global-all-co-prtnr-py-PartBadge-Mar2515-1) is now signed in the playstore 👍 

https://github.com/emoncms/AndroidApp/compare/master...glynhudson:master
